---
dependencies:
  - role: geerlingguy.mas
    vars:
      mas_installed_apps:
        - id: 747648890
          name: Telegram
        - id: 409203825
          name: Numbers
        - id: 409201541
          name: Pages
        - id: 409183694
          name: Keynote
        - id: 585829637
          name: Todoist