---
- name: Add required homebrew repos
  homebrew_tap:
    name: homebrew/cask-fonts

- name: Ensure console utils are installed
  apt:
    name:
      - bat
      - exa
      - git
      - nmap
      - telnet
      - docker
      - docker-compose
      - go
      - golangci-lint
      - neovim
      - fish
