---
- name: Ensure console utils are installed
  apt:
    name:
      - bat
      - exa
      - git
      - nmap
      - telnet
      - docker
      - docker-compose
      - neovim
      - fish

- name: Ensure golang are installed
  snap:
    name:
      - go
      - golangci-lint
    classic: true
