---
- name: Update all packages to the latest version
  apt:
    upgrade: dist

- name: Ensure console utils are installed
  apt:
    name:
      - bat
      - zsh
      - curl
      - git
      - nmap
      - telnet
      - docker
      - docker-compose
    state: present

# todo:
#- name: Ensure graphical utils are installed
#  homebrew_cask:
#    name:
#      - virtualbox
#      - postman
#      - discord
#      - sublime-text
#      - the-unarchiver
#      - teamviewer
#      - microsoft-word
#      - microsoft-excel
#      - microsoft-powerpoint
#      - figma