---
- name: Add required homebrew repos
  homebrew_tap:
    name: homebrew/cask-fonts

- name: Ensure console utils are installed
  homebrew:
    name:
      - bat
      - exa
      - git
      - nmap
      - telnet
      - docker
      - docker-compose
      - mkcert
      - go
      - golangci-lint
      - neovim

- name: Ensure graphical utils are installed
  homebrew_cask:
    name:
      - phpstorm
      - goland
      - postman
      - discord
      - sublime-text
      - the-unarchiver
      - teamviewer
      - microsoft-word
      - microsoft-excel
      - microsoft-powerpoint
      - figma
      - iterm2
