---
- name: Add required homebrew repos
  homebrew_tap:
    name: homebrew/cask-fonts

- name: Ensure console utils are installed
  homebrew:
    name:
      - bat
      - git
      - nmap
      - telnet
      - docker
      - docker-compose
      - mkcert
      - neovim
      - fish

- name: Ensure graphical utils are installed
  homebrew_cask:
    name:
      - phpstorm
      - goland
      - postman
      - discord
      - sublime-text
      - the-unarchiver
      - teamviewer
      - figma
      - iterm2
      - raycast
      - jetbrains-toolbox
      - obsidian
