---
- name: Ensure my productivity tools are installed
  homebrew_cask:
    name:
      - iina
      - loom
      - notion
      - slack
      - zoom
      # - acr
      - 1password
      - authy
      # - alt-tab
#      - deepl
#      - reverso

- name: Ensure my streaming tools are installed
  homebrew_cask:
    name:
      - obs

- name: MacOS settings
  osx_defaults:
    key: "{{ item.key }}"
    domain: "{{ item.domain }}"
    value: "{{ item.value }}"
  loop:
    - domain: com.apple.dock
      key: no-bouncing
      value: TRUE
