---
- name: Ensure my productivity tools are installed
  homebrew_cask:
    name:
      - google-chrome
      - iina
      - krisp
      - loom
      - notion
      - slack
      - skype
      - zoomus
      - microsoft-teams
      - macpass
      - authy

- name: Ensure my streaming tools are installed
  homebrew_cask:
    name:
      - obs

- name: MacOS settings
  osx_defaults:
    key: "{{ item.key }}"
    domain: "{{ item.domain }}"
    value: "{{ item.value }}"
  loop:
    - domain: com.apple.systempreferences
      key: AttentionPrefBundleIDs
      value: 0
    - domain: com.apple.systempreferences
      key: AppleFontSmoothing
      value: 0
    - domain: com.apple.dock
      key: no-bouncing
      value: TRUE