# todo:
#---
#- name: Ensure my productivity tools are installed
#  homebrew_cask:
#    name:
#      - google-chrome
#      - iina
#      - krisp
#      - loom
#      - notion
#      - slack
#      - skype
#      - zoomus
#      - microsoft-teams
#      - macpass
#      - authy